title: Lagomorph AI Documentation
description: Documentation for the Lagomorph AI 3D generator tool
theme: just-the-docs

url: https://damola90.github.io/lagomorph_docs

aux_links:
  Main Website: https://lagomorph.ai/
  Discord: https://discord.com/channels/1117841691408334898/1119312114742476860
