title: Lagomorph AI Documentation
description: Documentation for the Lagomorph AI 3D generator tool
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Main Website: https://lagomorph.ai/
